baseurl = "https://quan.io/"
theme = "cocoa-eh"
builddrafts = true
canonifyurls = true
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
publishdir = "public"
author = "Dan Quan"
title = "Dan Quan"
pluralizelisttitles = false
disableKinds = []

[permalinks]
blog = "blog/:slug/"

[params]
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "Software Engineer & Photographer"
copyright = "Copyright © 2019 Dan Quan"
copyrightUrl = "https://creativecommons.org/licenses/by-sa/4.0/"
logofile = ""
faviconfile = ""
highlightjs = true
progressively = true
share = false
latestpostcount = 5
github = "djquan"
email = "dan@quan.io"
linkedin = "dquan"
usesmallsummarycard = true
posts_navigation = true
githubRepo = "djquan/quan.io/tree/master"
small_banner_logo = false
tagicons = true

[params.utteranc]
enable = true
repo = "djquan/quan.io"
issueTerm = "title"

[params.colors]
identifier = "#527fc1f"
identifier_dark = "#1a3152"
trivial = "#6a7a8b"
foreground = "#181d2a"
background = "#f9f9f9"
background_dark = "#282a36"
code = "#87a5d2"
type = "#97d28b"
special = "#ffcb8d"
value = "#96c2d7"
statement = "#ff8e91"
