---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: quan-io
  namespace: quan-io
spec:
  selector:
    matchLabels:
      app: quan-io
  replicas: 2
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: quan-io
    spec:
      containers:
        - name: quan-io
          image: reg.quan.io/dan/quan.io:latest
          resources:
            requests:
              memory: "300Mi"
              cpu: "300m"
            limits:
              memory: "350Mi"
              cpu: "350m"
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 45
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 0
            successThreshold: 1
            failureThreshold: 3
      imagePullSecrets:
        - name: regcred-reg-quan-io
---
apiVersion: v1
kind: Service
metadata:
  name: quan-io-service
  namespace: quan-io
spec:
  selector:
    app: quan-io
  ports:
    - protocol: TCP
      port: 80
      name: web
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: quan-io-ingress
  namespace: quan-io
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header l5d-dst-override quan-io-service.quan-io.svc.cluster.local:80;
      proxy_hide_header l5d-remote-ip;
      proxy_hide_header l5d-server-id;
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - quan.io
      secretName: letsencrypt-prod
  rules:
    - host: quan.io
      http:
        paths:
          - backend:
              serviceName: quan-io-service
              servicePort: 80
