name: quan.io
on:
  push:
    branches:
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Login
        uses: actions/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push
        uses: actions/action-builder/docker@master
        with:
          entrypoint: make
          args: build push
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
      - uses: azure/k8s-actions/setup-kubectl@master
        with:
          version: v1.15.3
        env:
          RUNNER_TEMPDIRECTORY: ${RUNNER_TEMP}
          RUNNER_TOOLSDIRECTORY: ${RUNNER_TOOL_CACHE}
      - uses: azure/k8s-actions/k8s-set-context@master
        with:
          kubeconfig: "${{ secrets.KUBECONFIG }}"
      - name: Use SHA
        run: 'sed -ie "s/latest/$GITHUB_SHA/" kubernetes/application.yaml'
      - name: Deploy
        run: "kubectl apply -f kubernetes/application.yaml"
      - name: Wait for completion
        run: "kubectl rollout -n quan-io status deployment/quan-io"
        timeout-minutes: 8
      - name: Update Linkerd Service Profile
        run: "ruby script/generate_service_profile.rb | kubectl apply -f -"
